add_test( [==[[Linear] Linear Search]==] /home/susan/Documents/csi281/assignment02/assignment02_tests [==[--test-case=[Linear] Linear Search]==])
set_tests_properties( [==[[Linear] Linear Search]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment02 LABELS)
add_test( [==[[Binary] Binary Search]==] /home/susan/Documents/csi281/assignment02/assignment02_tests [==[--test-case=[Binary] Binary Search]==])
set_tests_properties( [==[[Binary] Binary Search]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment02 LABELS)
add_test( [==[[Random] Random Int Array]==] /home/susan/Documents/csi281/assignment02/assignment02_tests [==[--test-case=[Random] Random Int Array]==])
set_tests_properties( [==[[Random] Random Int Array]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment02 LABELS)
add_test( [==[[Speed] Array Search Speed]==] /home/susan/Documents/csi281/assignment02/assignment02_tests [==[--test-case=[Speed] Array Search Speed]==])
set_tests_properties( [==[[Speed] Array Search Speed]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment02 LABELS)
set( assignment02_tests_TESTS [==[[Linear] Linear Search]==] [==[[Binary] Binary Search]==] [==[[Random] Random Int Array]==] [==[[Speed] Array Search Speed]==])
