add_test( [==[[Bubble] Bubble Sort]==] /home/susan/Documents/csi281/assignment04/assignment04_tests [==[--test-case=[Bubble] Bubble Sort]==])
set_tests_properties( [==[[Bubble] Bubble Sort]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment04 LABELS)
add_test( [==[[Selection] Selection Sort]==] /home/susan/Documents/csi281/assignment04/assignment04_tests [==[--test-case=[Selection] Selection Sort]==])
set_tests_properties( [==[[Selection] Selection Sort]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment04 LABELS)
add_test( [==[[Insertion] Insertion Sort]==] /home/susan/Documents/csi281/assignment04/assignment04_tests [==[--test-case=[Insertion] Insertion Sort]==])
set_tests_properties( [==[[Insertion] Insertion Sort]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment04 LABELS)
add_test( [==[[Speed] Speed Comparison]==] /home/susan/Documents/csi281/assignment04/assignment04_tests [==[--test-case=[Speed] Speed Comparison]==])
set_tests_properties( [==[[Speed] Speed Comparison]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment04 LABELS)
set( assignment04_tests_TESTS [==[[Bubble] Bubble Sort]==] [==[[Selection] Selection Sort]==] [==[[Insertion] Insertion Sort]==] [==[[Speed] Speed Comparison]==])
