add_test( [==[[PriorityQueue<int>] PriorityQueue<int> test]==] /home/susan/Documents/csi281/assignment12/assignment12_tests [==[--test-case=[PriorityQueue<int>] PriorityQueue<int> test]==])
set_tests_properties( [==[[PriorityQueue<int>] PriorityQueue<int> test]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment12 LABELS)
add_test( [==[[PriorityQueue<string>] PriorityQueue<string> test]==] /home/susan/Documents/csi281/assignment12/assignment12_tests [==[--test-case=[PriorityQueue<string>] PriorityQueue<string> test]==])
set_tests_properties( [==[[PriorityQueue<string>] PriorityQueue<string> test]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment12 LABELS)
add_test( [==[[rand PriorityQueue<int>] random PriorityQueue<int> test]==] /home/susan/Documents/csi281/assignment12/assignment12_tests [==[--test-case=[rand PriorityQueue<int>] random PriorityQueue<int> test]==])
set_tests_properties( [==[[rand PriorityQueue<int>] random PriorityQueue<int> test]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment12 LABELS)
add_test( [==[[time PriorityQueue<int>] PriorityQueue<int> timing test]==] /home/susan/Documents/csi281/assignment12/assignment12_tests [==[--test-case=[time PriorityQueue<int>] PriorityQueue<int> timing test]==])
set_tests_properties( [==[[time PriorityQueue<int>] PriorityQueue<int> timing test]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment12 LABELS)
set( assignment12_tests_TESTS [==[[PriorityQueue<int>] PriorityQueue<int> test]==] [==[[PriorityQueue<string>] PriorityQueue<string> test]==] [==[[rand PriorityQueue<int>] random PriorityQueue<int> test]==] [==[[time PriorityQueue<int>] PriorityQueue<int> timing test]==])
