add_test( [==[[BST<int>] BST<int> test]==] /home/susan/Documents/csi281/assignment11/assignment11_tests [==[--test-case=[BST<int>] BST<int> test]==])
set_tests_properties( [==[[BST<int>] BST<int> test]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment11 LABELS)
add_test( [==[[BST<string>] BST<string> test]==] /home/susan/Documents/csi281/assignment11/assignment11_tests [==[--test-case=[BST<string>] BST<string> test]==])
set_tests_properties( [==[[BST<string>] BST<string> test]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment11 LABELS)
add_test( [==[[rand BST<int>] random BST<int> test]==] /home/susan/Documents/csi281/assignment11/assignment11_tests [==[--test-case=[rand BST<int>] random BST<int> test]==])
set_tests_properties( [==[[rand BST<int>] random BST<int> test]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment11 LABELS)
add_test( [==[[time BST<int>] BST<int> timing test]==] /home/susan/Documents/csi281/assignment11/assignment11_tests [==[--test-case=[time BST<int>] BST<int> timing test]==])
set_tests_properties( [==[[time BST<int>] BST<int> timing test]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment11 LABELS)
set( assignment11_tests_TESTS [==[[BST<int>] BST<int> test]==] [==[[BST<string>] BST<string> test]==] [==[[rand BST<int>] random BST<int> test]==] [==[[time BST<int>] BST<int> timing test]==])
