add_test( [==[[Merge] Merge Sort]==] /home/susan/Documents/csi281/assignment05/assignment05_tests [==[--test-case=[Merge] Merge Sort]==])
set_tests_properties( [==[[Merge] Merge Sort]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment05 LABELS)
add_test( [==[[Quick] Quicksort]==] /home/susan/Documents/csi281/assignment05/assignment05_tests [==[--test-case=[Quick] Quicksort]==])
set_tests_properties( [==[[Quick] Quicksort]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment05 LABELS)
add_test( [==[[Insertion] Insertion Sort]==] /home/susan/Documents/csi281/assignment05/assignment05_tests [==[--test-case=[Insertion] Insertion Sort]==])
set_tests_properties( [==[[Insertion] Insertion Sort]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment05 LABELS)
add_test( [==[[Hybrid] Hybrid Sort]==] /home/susan/Documents/csi281/assignment05/assignment05_tests [==[--test-case=[Hybrid] Hybrid Sort]==])
set_tests_properties( [==[[Hybrid] Hybrid Sort]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment05 LABELS)
add_test( [==[[Speed] Speed Comparison]==] /home/susan/Documents/csi281/assignment05/assignment05_tests [==[--test-case=[Speed] Speed Comparison]==])
set_tests_properties( [==[[Speed] Speed Comparison]==] PROPERTIES WORKING_DIRECTORY /home/susan/Documents/csi281/assignment05 LABELS)
set( assignment05_tests_TESTS [==[[Merge] Merge Sort]==] [==[[Quick] Quicksort]==] [==[[Insertion] Insertion Sort]==] [==[[Hybrid] Hybrid Sort]==] [==[[Speed] Speed Comparison]==])
